---
title: "Analysis of Gene Expression"
subtitle: "Transcriptional signature of prion-induced neurotoxicity in a Drosophila model of transmissible mammalian prion disease"
author: Niek Scholten
date: 07-05-22
output: pdf_document
---

```{r read-data, echo = T, results = 'hide'}
setwd("/home/nieks/PycharmProjects/Bio-Informatica-Hanze/Thema 07 - Analyse van Genexpressie/Praktijkopdracht")
data <- read.table("Data/GSE144028.txt")
```

```{r boxplot}
summary(data)
boxplot((data), outline = FALSE, col = 'green')

```

```{r densityplot}
library(affy)
library(scales)
myColors <- hue_pal()(12)

plotDensity(log2(data + 0.1), col=rep(myColors, each=3),
            lty=c(1:ncol(data)), xlab="Log2(count)",
            main="Expression Distribution")

legend('topright', names(data), lty=c(1:ncol(data)),
       col=rep(myColors, each=3),
       cex=0.32)  # Fix scale for knitted output
abline(v=-1.5, lwd=1, col='red', lty=2)
```
```{r DESeq}
library(DESeq2)

(ddsMat <- DESeqDataSetFromMatrix(countData = data,
                                  colData = data.frame(samples = names(data)),
                                  design = ~ 1))
rld.dds <- vst(ddsMat)
rld <- assay(rld.dds)

sampledists <- dist( t( rld ))
```
```{r heatmap}
library(pheatmap)

sampleDistMatrix <- as.matrix(sampledists)

annotation <- data.frame(Type = factor(rep(rep(1:2, each = 3), each = 6),
                                          labels = c("Normal Brain Homogenate", "Scrapie")))

rownames(annotation) <- names(counts)

pheatmap(sampleDistMatrix, show_colnames = FALSE,
         # annotation_col = annotation,  # Gives an error
         clustering_distance_rows = sampledists,
         clustering_distance_cols = sampledists,
         main = "Euclidian Sample Distances")
```
```{r MDS}
library(PoiClaClu)
library(ggplot2)

dds <- assay(ddsMat)
poisd <- PoissonDistance( t(dds) )

samplePoisDistMatrix <- as.matrix(poisd$dd)

mdsPoisData <- data.frame( cmdscale(samplePoisDistMatrix) )

names(mdsPoisData) <- c('x_coord', 'y_coord')

groups <- factor(rep(1:12, each=3),
                 labels = c("X51D_5_NBH",
                            "X51D_5_S",
                            "X51D_30_NBH",
                            "X51D_30_S",
                            "PrPCyt_5_NBH",
                            "PrPCyt_5_S",
                            "PrPCyt_30_NBH",
                            "PrPCyt_30_S",
                            "PrPGPI_5_NBH",
                            "PrPGPI_5_S",
                            "PrPGPI_40_NBH",
                            "PrPGPI_40_S"))
coldata <- names(data)

ggplot(mdsPoisData, aes(x_coord, y_coord, color = groups, label = coldata)) +
  geom_text(size = 4) +
  ggtitle('Multi Dimensional Scaling') +
  labs(x = "Poisson Distance", y = "Poisson Distance") +
  theme_bw()
```
Some samples clearly deviate from the other 2 in the group.
This is especially clear with X51D_5_S, PrPCyt_30_NBH, X51D_30_NBH & PrPCyt_5_S.
Strangely, these samples are all the first one in their respective group. This could indicate that the first tests were less accurate.
Since 3 samples must remain in each group, no data will be removed from the set.
